import type { TravelPackage } from '../../domain/entities/TravelPackage'

export const mockFeaturedPackages: TravelPackage[] = [
  {
    id: 'lf-sjo-airport',
    title: 'La Fortuna - San Jose Airport',
    destination: 'San Jose, Costa Rica',
    durationDays: 1,
    price: 175,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1552465881-721a37ffaf1f?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to San Jose Airport (3 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-sjo-downtown',
    title: 'La Fortuna - San Jose Downtown',
    destination: 'San Jose, Costa Rica',
    durationDays: 1,
    price: 207,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1552465881-721a37ffaf1f?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to downtown San Jose (3 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-liberia',
    title: 'La Fortuna - Liberia Airport',
    destination: 'Liberia, Costa Rica',
    durationDays: 1,
    price: 188,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Liberia Airport (3 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-papagayo',
    title: 'La Fortuna - Papagayo',
    destination: 'Papagayo, Costa Rica',
    durationDays: 1,
    price: 230,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Papagayo luxury resorts (3 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-tamarindo',
    title: 'La Fortuna - Tamarindo',
    destination: 'Tamarindo, Costa Rica',
    durationDays: 1,
    price: 278,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Tamarindo surf beach (4 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-poas',
    title: 'La Fortuna - Poas',
    destination: 'Poas, Costa Rica',
    durationDays: 1,
    price: 219,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Poas volcano area (1 hr 45 min).',
    isFeatured: true,
  },
  {
    id: 'lf-jaco',
    title: 'La Fortuna - Jaco',
    destination: 'Jaco, Costa Rica',
    durationDays: 1,
    price: 207,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Jaco beach town (4 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-manuel',
    title: 'La Fortuna - Manuel Antonio',
    destination: 'Manuel Antonio, Costa Rica',
    durationDays: 1,
    price: 279,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Manuel Antonio national park (5 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-rio-celeste',
    title: 'La Fortuna - Rio Celeste',
    destination: 'Rio Celeste, Costa Rica',
    durationDays: 1,
    price: 170,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Rio Celeste waterfall (1 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-guanacaste',
    title: 'La Fortuna - Guanacaste',
    destination: 'Guanacaste, Costa Rica',
    durationDays: 1,
    price: 218,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1470114716159-e389f8712fda?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer across Guanacaste (3 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-bajos',
    title: 'La Fortuna - Bajos del Toro',
    destination: 'Bajos del Toro, Costa Rica',
    durationDays: 1,
    price: 145,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Bajos del Toro (1 hr 45 min).',
    isFeatured: true,
  },
  {
    id: 'lf-monteverde',
    title: 'La Fortuna - Monteverde',
    destination: 'Monteverde, Costa Rica',
    durationDays: 1,
    price: 215,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Monteverde cloud forest (3 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-montezuma',
    title: 'La Fortuna - Montezuma',
    destination: 'Montezuma, Costa Rica',
    durationDays: 1,
    price: 215,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Montezuma beach town (5 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-dreams',
    title: 'La Fortuna - Dreams Las Mareas',
    destination: 'Las Mareas, Costa Rica',
    durationDays: 1,
    price: 376,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Dreams Las Mareas resort (4 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-catalinas',
    title: 'La Fortuna - Las Catalinas',
    destination: 'Las Catalinas, Costa Rica',
    durationDays: 1,
    price: 266,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Las Catalinas beach community (4 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-riu',
    title: 'La Fortuna - Riu Hotels',
    destination: 'Guanacaste, Costa Rica',
    durationDays: 1,
    price: 225,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Riu all-inclusive hotels (3 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-samara',
    title: 'La Fortuna - Samara',
    destination: 'Samara, Costa Rica',
    durationDays: 1,
    price: 328,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Samara beach (4 hr 30 min).',
    isFeatured: true,
  },
  {
    id: 'lf-puerto-viejo',
    title: 'La Fortuna - Puerto Viejo',
    destination: 'Puerto Viejo, Costa Rica',
    durationDays: 1,
    price: 352,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Caribbean Puerto Viejo (5 hr).',
    isFeatured: true,
  },
  {
    id: 'lf-sarapiqui',
    title: 'La Fortuna - Sarapiqui',
    destination: 'Sarapiqui, Costa Rica',
    durationDays: 1,
    price: 135,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    description: 'Private transfer to Sarapiqui river area (1 hr 30 min).',
    isFeatured: true,
  },
]
